Set — 3
Dynamic Memory Allocation using C/C++

Write a C/C++ program to display the size (in bytes) of the fundamental data types int, float, double, and char using the sizeof() operator. Display the observations in a well-formatted manner.
Write a program that dynamically allocates memory for a single variable of type int, float, and double (using malloc() in C or new in C++). For each allocated pointer, print the size of the memory block using sizeof(*pointer) and verify that it matches the size obtained in Q1.
Write a program that dynamically allocates an array of 5 elements of type int and a separate array of 5 elements of type double. Print the memory address of each element in both arrays. Observe and explain, in your own words, why the addresses in the int array increase by 4 while the addresses in the double array increase by 8. Use uintptr_t to cast the address to int.
A polling booth wants to record the age of every voter who casts a vote on election day, but the number of voters is unknown until the booth closes. Write a program that allocates an array dynamically to store voter ages as they arrive, and at the end computes and displays the number of voters below 30 & 60 and above.
A gym wants to expand its member check-in log during a promotional week, since the earlier fixed-size array is no longer enough. Write a program that first dynamically allocates an array for n check-ins, then uses realloc() to expand it when m additional walk-in members check in, and prints the updated total. [C++: new → copy → delete → new memory].
A company has two branches, each recording monthly sales for several products in a grid (rows = products, columns = months). Since the number of products (m) and months (n) changes each time, write a program that dynamically allocates two m × n grids (using pointer-to-pointer allocation), takes sales input for both, adds them cell by cell, displays the result, and frees all allocated memory. [C: int **arr = (int **)malloc(m * sizeof(int *))] [C++: int **arr = (int **)malloc(m * sizeof(int *));]
